import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false;

/* import specific icons */
import {
  faComments,
  faAnglesLeft,
  faAnglesRight,
  faArrowRight,
  faArrowLeft,
  faMagnifyingGlass,
  faPlus,
  faMinus,
  faAngleDown,
  faHandPointDown,
  faAngleRight,
  faCalendarDays,
  faChevronRight,
  faUserSecret,
  faLongArrowRight,
  faSpinner,
  faTimes,
  faHeart,
  faCaretUp,
  faCaretDown,
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faPaperPlane,
  faSave,
  faSearchPlus,
  faSearchMinus,
  faSearch,
  faStar,
  faStarHalfAlt,
  faArrowsAltV,
  faBroom,
  faDownload,
  faFileInvoice,
  faTimesCircle,
  faPencilAlt,
  faCheck,
  faUserCircle,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faExpand,
  faEllipsis,
  faEarthAmericas,
  faEllipsisH,
  faUserGroup,
  faLock,
  faGear,
  faBell,
  faQuestionCircle,
  faCog,
  faBars,
  faSortDown,
  faUser,
  faExclamationCircle,
  faAngleLeft,
  faPenNib,
  faTrash,
} from "@fortawesome/free-solid-svg-icons";

/* add icons to the library */
library.add(
  faComments,
  faAnglesLeft,
  faAnglesRight,
  faArrowRight,
  faArrowLeft,
  faMagnifyingGlass,
  faPlus,
  faMinus,
  faAngleDown,
  faHandPointDown,
  faAngleRight,
  faCalendarDays,
  faChevronRight,
  faUserSecret,
  faLongArrowRight,
  faSpinner,
  faTimes,
  faHeart,
  faCaretUp,
  faCaretDown,
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faPaperPlane,
  faSave,
  faSearchPlus,
  faSearchMinus,
  faSearch,
  faStar,
  faStarHalfAlt,
  faArrowsAltV,
  faBroom,
  faDownload,
  faFileInvoice,
  faTimesCircle,
  faPencilAlt,
  faCheck,
  faUserCircle,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faExpand,
  faEllipsis,
  faEarthAmericas,
  faEllipsisH,
  faUserGroup,
  faLock,
  faGear,
  faBell,
  faQuestionCircle,
  faCog,
  faBars,
  faSortDown,
  faUser,
  faExclamationCircle,
  faAngleLeft,
  faPenNib,
  faTrash
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("fa", FontAwesomeIcon);
});
